--- !ditz.rubyforge.org,2008-03-06/project 
name: elti
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: elti
- !ditz.rubyforge.org,2008-03-06/component 
  name: tresor
- !ditz.rubyforge.org,2008-03-06/component 
  name: robert
- !ditz.rubyforge.org,2008-03-06/component 
  name: other
releases: []

